### ISSUE TITLE
Unresolved external symbol when building native dependencies

### ISSUE THREAD

**Issue by fmc91** [zwcloud/CairoSharp#11]
Hi

I have tried to download the source code and build it, but I ran into a problem with this when building the native dependencies. I get the following output from build:
1>cairo-surface-observer.obj : error LNK2001: unresolved external symbol __cairo_script_context_create_internal
1>cairo-surface-observer.obj : error LNK2001: unresolved external symbol __cairo_script_context_attach_snapshots
1>C:\Users\fazal\Libraries\CairoSharp\source\Native\Output\bin\win-x64\cairo.dll : fatal error LNK1120: 2 unresolved externals

Any help with this would be greatly appreciated.

**Comment by zwcloud** [comment]
about [error LNK2001](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1112?view=msvc-160):

> The object files specified as input were compiled for different computer types.
> 
> For example, if you try to link an object file compiled with /clr and an object file compiled with /clr:pure (machine type CEE), the linker will generate the error LNK1112. The /clr:pure compiler option is deprecated in Visual Studio 2015 and unsupported in Visual Studio 2017.
> 
> Similarly, if you create one module with the x64 compiler and another module with the x86 compiler, and try to link them, the linker will generate LNK1112.
> 
> A possible reason for this error is if you are developing a 64-bit application but have not installed one of the Visual C++ 64-bit compilers. In this case, 64-bit configurations will not be available. To fix this issue, run the installer for Visual Studio and install the missing C++ components.
> 
> This error can also occur if you change the Active solution configuration in the Configuration Manager and then try to build the project before you delete the intermediate project files. To resolve this error, select Rebuild Solution from the Build menu. You can also select Clean Solution from the Build menu and then build the solution.

Please check if your build configuration is correctly set as described above.

I just tried to rebuild the native cairo project **with the default build configuration**, but no such error happened and finished successfully.
```text
Build started...
1>------ Build started: Project: cairo, Configuration: Debug x64 ------
1>cairo.vcxproj -> D:\Downloads\my\Projects\CairoSharp\source\Native\Output\bin\win-x64\cairod.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Make sure the source code is complete and try rebuilding.

**Comment by zwcloud** [comment]
Closed issue because no response and cannot reproduce. If anyone still run into this issue, please reply.
