### ISSUE TITLE
Missing Files in Release File

### ISSUE THREAD

**Issue by 8** [zwcloud/CairoSharp#4]
I've downloaded the release https://github.com/zwcloud/CairoSharp/releases/tag/dotnet_4.5 and found that the solution does not compile due to following 4 files are missing from the .zip and the tar.gz:

- Demo\Windows\WinFormDemo\Program.cs
- Demo\Windows\WinFormDemo\Form1.Designer.cs
- Demo\Windows\DrawPngInMemory\Program.cs
- Demo\Windows\DrawPngInMemory\Form1.cs

Take care,
Martin

**Comment by zwcloud** [comment]
Thanks, I will looking into this when I'm free.

**Comment by zwcloud** [comment]
fixed in https://github.com/zwcloud/CairoSharp/commit/116c3e30136ca4626536448daf95064c9fc79b55

updated release:
https://github.com/zwcloud/CairoSharp/releases/tag/dotnet45_v1
