### ISSUE TITLE
Draw text using Windows system fonts?

### ISSUE THREAD

**Issue by MatthiasSchilder** [zwcloud/CairoSharp#8]
Is it possible to draw text using one of the pre-installed Windows system fonts? I read in the cairo reference manual a little bit, and it seems like it somehow depends on which font backend is enabled in cairo. Seems to be a fairly complex topic.

**Comment by zwcloud** [comment]
@MatthiasSchilder You will need to use [PangoSharp](https://github.com/zwcloud/PangoSharp) together with CairoSharp. See https://github.com/zwcloud/PangoSharp/blob/master/Demos/Demo01_Shape/Program.cs#L8 for usage.

**Comment by MatthiasSchilder** [comment]
@zwcloud Thanks!

**Comment by MatthiasSchilder** [comment]
@zwcloud I'am now able to compile PangoSharp, all dependencies are fullfilled and the Demo01_Shape does what it is expected to. Unfortunately, I wasn't able to find out in which way PangoSharp supports different font backends? There is code for Win32FontFamilies and FT2, but it looks fairly unused to me.. are there any other libs neccessary, like freetype and maybe a .NET-wrapper for this?

**Comment by zwcloud** [comment]
> in which way PangoSharp supports different font backends?

I have no idea on that, but you can refer to [native pango docs](https://developer.gnome.org/pango/stable/pango-Fonts.html) for details on win32 font support. 
I can only remember that the key is to create a `PangoFontDescription`.

I think it's possible to use freetype to load font files and use the font in pango but have never tried that: https://developer.gnome.org/pango/stable/pango-FreeType-Fonts-and-Rendering.html

You may also be interested in other text rendering lib for C#/.NET:
* [Typography](https://github.com/LayoutFarm/Typography) (Pure C# and it is the one I'm using in my project [ImGui](https://github.com/zwcloud/ImGui))
* [StbTruetypeSharp](https://github.com/zwcloud/StbTruetypeSharp) (You will need to use [stb_rect_pack](https://github.com/nothings/stb/blob/master/stb_rect_pack.h) for text layouting. But there is no C# wrapper for that yet.)

Good luck.

**Comment by MatthiasSchilder** [comment]
I wanted to give you some feedback.
In the end, we decided to just do it in C++. We now have a small native DLL, which exports a function that uses cairo and freetype to create and draw the glyphs for a certain string and font. The fonts are loaded from a system TrueTypeFont (ttf) or OpenType file, which is specified by an absolute path. 

This function also takes a cairo context. We then added a NativeMethod-import to CairoSharp, which calls this function and exposes it through the Context. 

Nice side-effect is, the dependency to Pango / PangoSharp is gone and so the rather extensive dependencies to GLib and whatsoever.. The code is still a little bit bleeding edge, but the rendering of random fonts looks pretty decent. 

By the way, we extended CairoSharp so that SVG output to .NET-streams is possible. Should we file a pull request, or do you know something which contradicts enabling it?

**Comment by zwcloud** [comment]
> Nice side-effect is, the dependency to Pango / PangoSharp is gone and so the rather extensive dependencies to GLib and whatsoever..

The extensive dependencies brought by pango... That's why I decided not to use Pango in my project.

> By the way, we extended CairoSharp so that SVG output to .NET-streams is possible. Should we file a pull request, or do you know something which contradicts enabling it?

We should follow [the same API structure in native cairo for SVG](https://www.cairographics.org/manual/cairo-SVG-Surfaces.html). Please file a pull-request so I can review it and then properly integrate it with existing code.

**Comment by MatthiasSchilder** [comment]
> We should follow [the same API structure in native cairo for SVG](https://www.cairographics.org/manual/cairo-SVG-Surfaces.html). Please file a pull-request so I can review it and then properly integrate it with existing code.

Yes, it just wraps cairo_svg_surface_create_for_stream(). I'll do it next monday.
